#!/usr/bin/env python3
"""Push the gallery to 500 works."""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE / "data"

NEW_WORKS: dict[str, list[dict]] = {
    "africa": [
        {
            "title": "Great Mosque of Kano",
            "meta": "Hausa · 15th c. onward · Nigeria",
            "desc": "A mud-and-stick Friday mosque rebuilt many times across six centuries. The current building rose after a 1937 fire; minarets slender as reeds above a walled city.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Kano_Mosque_in_1960.jpg/960px-Kano_Mosque_in_1960.jpg",
            "year": 1500,
        },
        {
            "title": "Kuba Appliqué Textiles",
            "meta": "Kuba Kingdom · 17th c. onward · DR Congo",
            "desc": "Raffia cloth embroidered with cut-pile geometrics. Men weave the base; women embroider. No two patterns repeat — each is a one-time composition.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/6/6c/COLLECTIE_TROPENMUSEUM_Een_Bakuba_vrouw_met_scarificaties_op_haar_buik_borduurt_een_mat_Congo_TMnr_60033932.jpg",
            "year": 1800,
        },
        {
            "title": "Tuareg Metalwork",
            "meta": "Tuareg · 18th c. onward · Sahara",
            "desc": "Silver crosses, amulet cases, saddle fittings. Each Tuareg town has a signature cross shape; the Agadez cross is the most widely reproduced.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Homme_toureg.jpg/960px-Homme_toureg.jpg",
            "year": 1850,
        },
        {
            "title": "Akuaba",
            "meta": "Akan · traditional · Ghana",
            "desc": "Wooden fertility figures carried by women hoping to conceive. Small, abstracted, round-faced. Carved also now for collectors; the sacred ones are never sold.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/e/e7/Akuaba.jpg",
            "year": 1900,
        },
        {
            "title": "Djinguereber Mosque",
            "meta": "Mali Empire · 1327 · Timbuktu",
            "desc": "Commissioned by Mansa Musa after his pilgrimage to Mecca. An Andalusian architect built it in earth and fossil limestone — one of three medieval mosques still standing in Timbuktu.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Djingareiber_cour.jpg/960px-Djingareiber_cour.jpg",
            "year": 1327,
        },
        {
            "title": "Sowei Helmet Mask",
            "meta": "Mende · 19th c. onward · Sierra Leone",
            "desc": "A black helmet mask worn in the Sande women's society initiation — the only African mask tradition danced exclusively by women, representing ideals of beauty and comportment.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Brooklyn_Museum_69.39.2_Helmet_Mask_ndoli_jowei_for_Sande_Society_%282%29.jpg/960px-Brooklyn_Museum_69.39.2_Helmet_Mask_ndoli_jowei_for_Sande_Society_%282%29.jpg",
            "year": 1870,
        },
        {
            "title": "Zulu Beadwork",
            "meta": "Zulu · 19th c. onward · South Africa",
            "desc": "Glass trade beads sewn onto leather and cotton in geometric patterns — colors and combinations encoding courtship messages (\"love letters\" in bead).",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Zulu_Culture%2C_KwaZulu-Natal%2C_South_Africa_%2820325329170%29.jpg/960px-Zulu_Culture%2C_KwaZulu-Natal%2C_South_Africa_%2820325329170%29.jpg",
            "year": 1880,
        },
        {
            "title": "Fasil Ghebbi",
            "meta": "Ethiopian · 17th c. · Gondar",
            "desc": "A fortress-city of stone castles built by a succession of Solomonic emperors. The European-looking keeps are misleading — they're Ethiopian invention, not import.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Fasilides_Palace_01.jpg/960px-Fasilides_Palace_01.jpg",
            "year": 1640,
        },
    ],
    "egypt-nubia": [
        {
            "title": "Temple of Seti I at Abydos",
            "meta": "New Kingdom · c. 1290 BCE",
            "desc": "An L-shaped temple with seven chapels. Its Abydos King List carved on one corridor became a key scholarly tool — naming 76 pharaohs back to the First Dynasty.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/3/33/AbydosFacade.jpg",
            "year": -1290,
        },
        {
            "title": "Beni Hasan",
            "meta": "Middle Kingdom · c. 1900 BCE",
            "desc": "Thirty-nine rock-cut tombs of provincial governors, walls painted with daily life — wrestling matches, bakers, looms, dancers — a rare survival of Middle Kingdom domestic art.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Exterior_view_of_tombs_of_Khety_and_Barquet_III.JPG/960px-Exterior_view_of_tombs_of_Khety_and_Barquet_III.JPG",
            "year": -1900,
        },
        {
            "title": "Merneptah Stele",
            "meta": "New Kingdom · 1208 BCE",
            "desc": "Black granite stele listing the pharaoh's victories. Line 27 contains the earliest known mention of \"Israel\" in any historical record.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Merneptah_Steli_%28cropped%29.jpg/960px-Merneptah_Steli_%28cropped%29.jpg",
            "year": -1208,
        },
        {
            "title": "Red Pyramid",
            "meta": "Old Kingdom · Sneferu · c. 2575 BCE · Dahshur",
            "desc": "Sneferu's third pyramid — the first true smooth-sided pyramid to work. Named for the reddish limestone exposed after the original white casing was stripped for later buildings.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Rote_Pyramide_%28Dahschur%29_04.jpg/960px-Rote_Pyramide_%28Dahschur%29_04.jpg",
            "year": -2575,
        },
        {
            "title": "Valley of the Kings",
            "meta": "New Kingdom · c. 1550–1070 BCE · West Bank, Thebes",
            "desc": "Sixty-five painted tombs cut into the limestone valley. The pharaohs chose it for its isolation — looters found everything anyway, except Tutankhamun.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/0/0c/Luxor%2C_Tal_der_K%C3%B6nige_%281995%2C_860x605%29.jpg",
            "year": -1300,
        },
        {
            "title": "White Chapel of Senusret I",
            "meta": "Middle Kingdom · c. 1950 BCE · Karnak",
            "desc": "A small bark chapel of fine white limestone. Torn down as filler in a later pylon; found reassembled piece by piece and reconstructed in the 1930s.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/White_Chapel.jpg/960px-White_Chapel.jpg",
            "year": -1950,
        },
        {
            "title": "Younger Memnon (Ramesses II)",
            "meta": "New Kingdom · c. 1250 BCE",
            "desc": "A granite colossus of Ramesses II. Belzoni dragged it out of the Ramesseum in 1816 and shipped it to the British Museum. Shelley saw it — and wrote Ozymandias.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Ramses_II_British_Museum.jpg/960px-Ramses_II_British_Museum.jpg",
            "year": -1250,
        },
        {
            "title": "Colossal Statue of Ramesses II",
            "meta": "New Kingdom · c. 1250 BCE · Grand Egyptian Museum",
            "desc": "Eleven meters of carved granite, 83 tons. Moved from downtown Cairo to the Grand Egyptian Museum in a 2006 road spectacle so large they had to raise bridges.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Grand_Egyptian_Museum_2019-11-07d.jpg/960px-Grand_Egyptian_Museum_2019-11-07d.jpg",
            "year": -1250,
        },
    ],
    "mesopotamia-persia": [
        {
            "title": "Code of Ur-Nammu",
            "meta": "Neo-Sumerian · c. 2100 BCE",
            "desc": "The oldest known written law code, predating Hammurabi by three centuries. The laws are oddly lenient — mostly fines, only occasional death.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/7/71/Ur_Nammu_code_Istanbul.jpg",
            "year": -2100,
        },
        {
            "title": "Ebla",
            "meta": "Early Bronze Age · c. 2500–1600 BCE · Syria",
            "desc": "A Syrian city-state whose palace archive held 20,000 cuneiform tablets in a previously unknown Semitic language. Discovered in the 1970s — changed the textbook on the Bronze Age Levant.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/HPIM3078_1.JPG/960px-HPIM3078_1.JPG",
            "year": -2300,
        },
        {
            "title": "Mari Ziggurat",
            "meta": "Early Dynastic → Old Babylonian · c. 2500–1750 BCE · Syria",
            "desc": "A trading capital on the middle Euphrates. Its palace mural of a royal investiture is one of the oldest paintings on plaster to survive.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/MariZiggurat.jpg/960px-MariZiggurat.jpg",
            "year": -2200,
        },
        {
            "title": "Tell Halaf",
            "meta": "Early Iron Age · 10th c. BCE · Syria",
            "desc": "Aramean palace built of basalt orthostats — grim, angular statues of gods, scorpions, and lions. Bombed to rubble in Berlin in 1943; a team spent decades reassembling 27,000 fragments.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/TellHalaf%2CNE-palace1.jpg/960px-TellHalaf%2CNE-palace1.jpg",
            "year": -900,
        },
        {
            "title": "Dur-Sharrukin (Khorsabad)",
            "meta": "Neo-Assyrian · Sargon II · 713–706 BCE",
            "desc": "The capital Sargon II built from scratch and moved into — only to be killed on campaign and abandoned by his heir. Its 40-ton alabaster lamassus now guard the Louvre and the Oriental Institute.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Lammasu.jpg/960px-Lammasu.jpg",
            "year": -710,
        },
        {
            "title": "Hittite Seated Deity",
            "meta": "Hittite Empire · 13th c. BCE · Anatolia",
            "desc": "A cast bronze figure in a high conical headdress. The lost Hittite pantheon ran to thousands of names — only a handful survive in objects like this one.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/c/c1/HittiteSeatedDeityAnatolia13thCenturyBCE.jpg",
            "year": -1250,
        },
    ],
    "mediterranean": [
        {
            "title": "Antikythera Mechanism",
            "meta": "Hellenistic · c. 150–100 BCE · Greece",
            "desc": "A corroded bronze device pulled from a Roman shipwreck in 1901. CT scans finally revealed: a geared orrery predicting sun, moon, and five planets. No surviving match until the Renaissance.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Antikythera_Fragment_A_%28Front%29.webp/960px-Antikythera_Fragment_A_%28Front%29.webp.png",
            "year": -120,
        },
        {
            "title": "Dipylon Amphora",
            "meta": "Geometric Greek · c. 750 BCE",
            "desc": "A grave marker nearly five feet tall, painted with stylized mourners in a prothesis scene. The moment figurative imagery returns to Greek pottery after five centuries of pure geometry.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Grave_amphora._8th_cent._B.C.jpg/960px-Grave_amphora._8th_cent._B.C.jpg",
            "year": -750,
        },
        {
            "title": "Treasury of Atreus",
            "meta": "Mycenaean · c. 1250 BCE · Mycenae",
            "desc": "A tholos tomb — a stone beehive thirteen meters high, held up only by its own corbelled weight. For fifteen centuries, the largest dome in the world.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Treasury_of_Atreus_Mycenae.jpg/960px-Treasury_of_Atreus_Mycenae.jpg",
            "year": -1250,
        },
        {
            "title": "Arch of Titus",
            "meta": "Roman Imperial · 81 CE · Rome",
            "desc": "Triumphal arch for the sack of Jerusalem. Its inner relief shows the Menorah and other temple spoils being carried in procession — our earliest image of the Second Temple's contents.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Arch_Titus%2C_Forum_Romanum%2C_Rome%2C_Italy.jpg/960px-Arch_Titus%2C_Forum_Romanum%2C_Rome%2C_Italy.jpg",
            "year": 81,
        },
        {
            "title": "Library of Celsus at Ephesus",
            "meta": "Roman Imperial · 110–135 CE · Turkey",
            "desc": "Two-story facade of a library that held 12,000 scrolls and the sarcophagus of its founder in a chamber behind the wall — a library as a tomb.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Ephesus_Celsus_Library_Fa%C3%A7ade.jpg/960px-Ephesus_Celsus_Library_Fa%C3%A7ade.jpg",
            "year": 125,
        },
        {
            "title": "Mausoleum at Halicarnassus",
            "meta": "Greek · c. 350 BCE · Turkey",
            "desc": "Tomb of the Carian satrap Mausolus, so grand that his name became the word for any lavish tomb. Wonder of the ancient world; shaken down by earthquakes; its fragments in the British Museum.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/5/5e/Mausoleum_at_Halicarnassus_at_the_Bodrum_Museum_of_Underwater_Archaeology.jpg",
            "year": -350,
        },
        {
            "title": "Phaistos Disc",
            "meta": "Minoan · c. 1700 BCE · Crete",
            "desc": "A fired clay disk stamped with 241 signs in a spiral. Still undeciphered. One of the earliest known uses of movable type — by more than 2,500 years.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Phaistos_Disc_%E2%80%94_Side_A.jpg/960px-Phaistos_Disc_%E2%80%94_Side_A.jpg",
            "year": -1700,
        },
        {
            "title": "Euphronios Krater",
            "meta": "Archaic Greek · Euphronios &amp; Euxitheos · c. 515 BCE",
            "desc": "A red-figure calyx-krater showing Hypnos and Thanatos carrying Sarpedon's body. Looted from an Etruscan tomb; caught up in a 30-year dispute; finally returned to Italy in 2008.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Eufronio%2C_cratere_modellato_da_euxitheos_con_morte_di_sarpedone%2C_520-510_ac_ca.%2C_dalla_necropoli_di_greppe_sant%27angelo_01.jpg/960px-Eufronio%2C_cratere_modellato_da_euxitheos_con_morte_di_sarpedone%2C_520-510_ac_ca.%2C_dalla_necropoli_di_greppe_sant%27angelo_01.jpg",
            "artist": "Euphronios",
            "year": -515,
        },
    ],
    "europe": [
        {
            "title": "Palace of Versailles",
            "meta": "French Baroque · 1661 onward · France",
            "desc": "Louis XIV's hunting lodge turned seat of French monarchy. The Hall of Mirrors reflects the west-facing garden at sunset; every piece of furniture was once pure silver.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Versailles-Chateau-Jardins02.jpg/960px-Versailles-Chateau-Jardins02.jpg",
            "year": 1680,
        },
        {
            "title": "Santiago de Compostela Cathedral",
            "meta": "Romanesque · 1075–1211 · Galicia",
            "desc": "The end of the Camino de Santiago — pilgrims walk 800 kilometers to this high altar and the silver tomb of St. James. The Botafumeiro swings eighty feet across the transept at mass.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Santiago_cathedral_2021.jpg/960px-Santiago_cathedral_2021.jpg",
            "year": 1150,
        },
        {
            "title": "Saturn Devouring His Son",
            "meta": "Black Paintings · 1819–1823",
            "desc": "Goya painted it on the wall of his dining room. Old, deaf, sick, he let Saturn eat his son with hollow eyes. Transferred to canvas after his death; not meant for anyone to see.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg/960px-Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg",
            "artist": "Francisco Goya",
            "year": 1821,
        },
        {
            "title": "Sistine Madonna",
            "meta": "High Renaissance · 1512–1513 · Dresden",
            "desc": "Mary descending on clouds; two bored cherubs resting their chins on the painting's lower frame. Those cherubs — cropped, enlarged, spun off — became one of the most reproduced images of any era.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/RAFAEL_-_Madonna_Sixtina_%28Gem%C3%A4ldegalerie_Alter_Meister%2C_Dresden%2C_1513-14._%C3%93leo_sobre_lienzo%2C_265_x_196_cm%29.jpg/960px-RAFAEL_-_Madonna_Sixtina_%28Gem%C3%A4ldegalerie_Alter_Meister%2C_Dresden%2C_1513-14._%C3%93leo_sobre_lienzo%2C_265_x_196_cm%29.jpg",
            "artist": "Raphael",
            "year": 1513,
        },
        {
            "title": "Café Terrace at Night",
            "meta": "Post-Impressionism · 1888 · Arles",
            "desc": "The yellow terrace still stands in Arles (renamed after the painting). No black in the night sky — deep cobalt blue everywhere instead. Van Gogh's first major work done at night.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Vincent_van_Gogh_%281853-1890%29_Caf%C3%A9terras_bij_nacht_%28place_du_Forum%29_Kr%C3%B6ller-M%C3%BCller_Museum_Otterlo_23-8-2016_13-35-40.JPG/960px-Vincent_van_Gogh_%281853-1890%29_Caf%C3%A9terras_bij_nacht_%28place_du_Forum%29_Kr%C3%B6ller-M%C3%BCller_Museum_Otterlo_23-8-2016_13-35-40.JPG",
            "artist": "Vincent van Gogh",
            "year": 1888,
        },
        {
            "title": "The Potato Eaters",
            "meta": "Early Van Gogh · 1885 · Nuenen",
            "desc": "Dark, muddy, deliberately ugly. Van Gogh wrote that he wanted to show hands that had dug the earth eating the potatoes those hands had grown. His breakthrough, though critics hated it.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Van-willem-vincent-gogh-die-kartoffelesser-03850.jpg/960px-Van-willem-vincent-gogh-die-kartoffelesser-03850.jpg",
            "artist": "Vincent van Gogh",
            "year": 1885,
        },
        {
            "title": "The Ambassadors",
            "meta": "Northern Renaissance · 1533",
            "desc": "Two French diplomats stand beside a table of instruments — lutes, globes, sundials. At the bottom, a distorted smear that becomes a human skull when you look from the side. A memento mori in code.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Hans_Holbein_the_Younger_-_The_Ambassadors_-_Google_Art_Project.jpg/960px-Hans_Holbein_the_Younger_-_The_Ambassadors_-_Google_Art_Project.jpg",
            "artist": "Hans Holbein the Younger",
            "year": 1533,
        },
        {
            "title": "Self-Portrait as the Allegory of Painting",
            "meta": "Baroque · c. 1638–1639",
            "desc": "Artemisia paints herself in the act of painting — arms muscled, sleeves pushed up. She was the first woman admitted to the Accademia di Belle Arti di Firenze.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Self-portrait_as_the_Allegory_of_Painting_%28La_Pittura%29_-_Artemisia_Gentileschi.jpg/960px-Self-portrait_as_the_Allegory_of_Painting_%28La_Pittura%29_-_Artemisia_Gentileschi.jpg",
            "artist": "Artemisia Gentileschi",
            "year": 1638,
        },
        {
            "title": "Siena Cathedral",
            "meta": "Italian Gothic · 1196–1348",
            "desc": "Striped in black and white marble. The floor is inlaid with 56 narrative panels — the largest program of marble intarsia in Italy, covered most of the year to protect it.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Duomo_di_Siena-9635.jpg/960px-Duomo_di_Siena-9635.jpg",
            "year": 1250,
        },
        {
            "title": "St. Peter's Basilica",
            "meta": "Renaissance &amp; Baroque · 1506–1626 · Vatican",
            "desc": "Built over the tomb of Peter. Bramante started it, Michelangelo finished the dome, Bernini added the piazza's embracing colonnade — the collective monument of Renaissance Rome.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Basilica_di_San_Pietro_in_Vaticano_September_2015-1a.jpg/960px-Basilica_di_San_Pietro_in_Vaticano_September_2015-1a.jpg",
            "year": 1600,
        },
        {
            "title": "Byzantine Mosaics of Hagia Sophia",
            "meta": "Byzantine · 867 CE onward · Constantinople",
            "desc": "Figural mosaics on gold ground. The Virgin and Child in the apse, unveiled in 867 to reverse the Iconoclasm, glows from half a kilometer away.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Hagia_Sophia_Interior_Virgin_2007.JPG/960px-Hagia_Sophia_Interior_Virgin_2007.JPG",
            "year": 867,
        },
        {
            "title": "Pala d'Oro",
            "meta": "Byzantine → Gothic goldwork · 976–1345 · Venice",
            "desc": "The golden altarpiece of San Marco. 250 enameled panels, 1,927 gems, looted from Constantinople in 1204 and then added to across four centuries. Still in daily use.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Venise%2C_Pala_d%27Oro_expos%C3%A9e.JPG/960px-Venise%2C_Pala_d%27Oro_expos%C3%A9e.JPG",
            "year": 1105,
        },
        {
            "title": "Rose Window",
            "meta": "Gothic · 13th c. · Strasbourg",
            "desc": "A massive tracery wheel of stained glass — the Gothic cathedral's visual sermon, laying out salvation in colored light. Chartres' rose blue was never surpassed; Strasbourg's west rose is a rival.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/b/bf/Strassburg_Rose_exterior.jpg",
            "year": 1280,
        },
        {
            "title": "Saint Sophia Cathedral, Kyiv",
            "meta": "Byzantine / Kyivan Rus · 1037 · Ukraine",
            "desc": "A Byzantine five-nave cathedral at the heart of Kyivan Rus. Its mosaics of the Virgin Orans (\"Indestructible Wall\") are said to have protected the city through a thousand years of war.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/80-391-0151_Kyiv_St.Sophia%27s_Cathedral_RB_18_2_%28cropped%29.jpg/960px-80-391-0151_Kyiv_St.Sophia%27s_Cathedral_RB_18_2_%28cropped%29.jpg",
            "year": 1037,
        },
    ],
    "islamic-world": [
        {
            "title": "Aljafería Palace",
            "meta": "Taifa · 11th c. · Zaragoza",
            "desc": "A fortified palace of the Banu Hud dynasty with a surviving Islamic core — interlaced polylobed arches, stucco arabesques. Now shares a building with the regional parliament.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Aljafer%C3%ADa_Palace.jpg/960px-Aljafer%C3%ADa_Palace.jpg",
            "year": 1070,
        },
        {
            "title": "Faisal Mosque",
            "meta": "Modern Islamic · 1986 · Islamabad",
            "desc": "A Turkish architect's vision of a Bedouin tent rendered in reinforced concrete and granite. One of the largest mosques in the world; a sharp-edged rejection of dome-and-minaret convention.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Ali_Mujtaba_WLM2017_FAISAL_MOSQUE_019.jpg/960px-Ali_Mujtaba_WLM2017_FAISAL_MOSQUE_019.jpg",
            "year": 1986,
        },
        {
            "title": "Hassan II Mosque",
            "meta": "Modern Moroccan · 1986–1993 · Casablanca",
            "desc": "Built out over the Atlantic on the king's sixtieth birthday. Its minaret is 210 meters — the second-tallest in the world. The hall's retractable roof opens to the sky.",
            "image": "https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/Hassan_II_mosque%2C_Casablanca_2.jpg/960px-Hassan_II_mosque%2C_Casablanca_2.jpg",
            "year": 1993,
        },
        {
            "title": "Mausoleum of Khoja Ahmed Yasawi",
            "meta": "Timurid · 1389–1405 · Turkistan, Kazakhstan",
            "desc": "Commissioned by Timur for a Sufi poet's tomb. Left unfinished when Timur died; the scaffolding on the portal front is six centuries old.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/%D0%9C%D0%B0%D1%83%D0%B7%D0%BE%D0%BB%D0%B5%D1%98_%D0%A5%D0%BE%D0%B4%D0%B6%D0%B5_%D0%90%D1%85%D0%BC%D0%B5%D0%B4%D0%B0_%D0%88%D0%B0%D1%81%D0%B0%D0%B2%D0%B8%D1%98%D0%B0_%28%D0%B3%D1%80%D0%B0%D0%B4_%D0%A2%D1%83%D1%80%D0%BA%D0%B5%D1%81%D1%82%D0%B0%D0%BD%2C_%D0%9A%D0%B0%D0%B7%D0%B0%D1%85%D1%81%D1%82%D0%B0%D0%BD%29.jpg/960px-%D0%9C%D0%B0%D1%83%D0%B7%D0%BE%D0%BB%D0%B5%D1%98_%D0%A5%D0%BE%D0%B4%D0%B6%D0%B5_%D0%90%D1%85%D0%BC%D0%B5%D0%B4%D0%B0_%D0%88%D0%B0%D1%81%D0%B0%D0%B2%D0%B8%D1%98%D0%B0_%28%D0%B3%D1%80%D0%B0%D0%B4_%D0%A2%D1%83%D1%80%D0%BA%D0%B5%D1%81%D1%82%D0%B0%D0%BD%2C_%D0%9A%D0%B0%D0%B7%D0%B0%D1%85%D1%81%D1%82%D0%B0%D0%BD%29.jpg",
            "year": 1400,
        },
        {
            "title": "Mshatta Facade",
            "meta": "Umayyad · 743–744 · Jordan",
            "desc": "A desert palace facade dismantled and shipped to Berlin in 1903 as a diplomatic gift. Carved rosettes and winged lions in the softest yellow sandstone; too brittle to move today.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Mschatta-Fassade_%28Pergamonmuseum%29.jpg/960px-Mschatta-Fassade_%28Pergamonmuseum%29.jpg",
            "year": 743,
        },
        {
            "title": "Qusayr 'Amra",
            "meta": "Umayyad · c. 723 · Jordan",
            "desc": "A desert bath complex covered inside with frescoes of wrestlers, bathing women, and the six kings of the world — Caesar, Negus, Khosrow — defeated or soon to be defeated by Islam.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Qusayr_Amra.jpg/960px-Qusayr_Amra.jpg",
            "year": 723,
        },
        {
            "title": "Shalamar Gardens",
            "meta": "Mughal · Shah Jahan · 1641 · Lahore",
            "desc": "Three terraces of Persian-style paradise garden, 400 fountains fed by a canal that once ran from the Himalayas. Listed in danger after colonial-era road-widening destroyed the outer walls.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Reflection_of_Farah_Baksh_Terrace_%28Upper_Terrace%29_main_building.jpg/960px-Reflection_of_Farah_Baksh_Terrace_%28Upper_Terrace%29_main_building.jpg",
            "year": 1641,
        },
        {
            "title": "Tomb of I'timād-ud-Daulah",
            "meta": "Mughal · 1622–1628 · Agra",
            "desc": "\"The Baby Taj\" — the first Mughal tomb clad entirely in white marble and inlaid with pietra dura. Built by Nur Jahan for her father; the stylistic prototype for the Taj Mahal eight years later.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/I%27tim%C4%81d-ud-Daulah%2C_Agra.jpg/960px-I%27tim%C4%81d-ud-Daulah%2C_Agra.jpg",
            "year": 1625,
        },
    ],
    "south-asia": [
        {
            "title": "Harappa",
            "meta": "Indus Valley Civilization · c. 2600–1900 BCE · Pakistan",
            "desc": "One of the two great Indus cities, grid-planned like Mohenjo-daro. Its granary, citadel, and burial mounds lie under centuries of British railway ballast quarried from the ruins.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/View_of_Granary_and_Great_Hall_on_Mound_F_-_Archaeological_site_of_Harappa.jpg/960px-View_of_Granary_and_Great_Hall_on_Mound_F_-_Archaeological_site_of_Harappa.jpg",
            "year": -2500,
        },
        {
            "title": "Priest-King of Mohenjo-daro",
            "meta": "Indus Valley · c. 2000 BCE · Pakistan",
            "desc": "A small bearded steatite bust, head-band and trefoil-patterned robe. Its title is a guess: we don't know if Mohenjo-daro had priests, kings, or this man at all.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/d/df/Mohenjo-daro_Priesterk%C3%B6nig.jpeg",
            "year": -2000,
        },
        {
            "title": "Pashupati Seal",
            "meta": "Indus Valley · c. 2350–2000 BCE",
            "desc": "A steatite seal of a seated, horned figure surrounded by animals — sometimes read as a proto-Shiva, sometimes a shaman. We can't read the script that runs along the top.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Shiva_Pashupati.jpg",
            "year": -2175,
        },
        {
            "title": "Buddhas of Bamiyan",
            "meta": "Greco-Buddhist · 6th c. · Afghanistan",
            "desc": "Two standing Buddhas, 38 and 55 meters tall, carved into a sandstone cliff on the Silk Road. The Taliban dynamited them in 2001; projection mapping now fills the empty niches on quiet nights.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/4/46/Buddha_of_Bamiyan.jpg",
            "year": 570,
        },
        {
            "title": "Dhamek Stupa",
            "meta": "Gupta era · 500 CE · Sarnath",
            "desc": "Solid brick stupa marking the spot of the Buddha's first sermon. Its upper band of geometric floral carving is some of the finest Gupta ornament anywhere.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Dhamek_Stupa%2C_Sarnath.jpg/960px-Dhamek_Stupa%2C_Sarnath.jpg",
            "year": 500,
        },
    ],
    "east-asia": [
        {
            "title": "Shigaraki Ware",
            "meta": "Muromachi onward · 13th c. · Shiga",
            "desc": "Earthy brown stoneware with feldspar eruptions on the surface. Prized for tea — the accidental \"fire colors\" and ash deposits are the whole point.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/241109_Tanikangama_Shigaraki_Koka_Shiga_pref_Japan14s3.jpg/960px-241109_Tanikangama_Shigaraki_Koka_Shiga_pref_Japan14s3.jpg",
            "year": 1300,
        },
        {
            "title": "Travelers Among Mountains and Streams",
            "meta": "Northern Song · Fan Kuan · c. 1000 CE",
            "desc": "A seven-foot hanging scroll — a sheer cliff dominates two-thirds of the picture. Tiny travelers and mules cross the foreground, dwarfed. Widely considered the greatest Chinese landscape painting.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fan_Kuan_-_Travelers_Among_Mountains_and_Streams_-_Google_Art_Project.jpg/960px-Fan_Kuan_-_Travelers_Among_Mountains_and_Streams_-_Google_Art_Project.jpg",
            "artist": "Fan Kuan",
            "year": 1000,
        },
        {
            "title": "Jōmon Flame Pottery",
            "meta": "Jōmon · c. 3000 BCE · Japan",
            "desc": "Clay pots with rims twisted into exuberant \"flame\" shapes. Made by prehistoric hunter-gatherers — and, at 15,000 years old, among the oldest pottery traditions on earth.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Jomon_Flame_Style_Pottery%2C_3000_BC.jpg/960px-Jomon_Flame_Style_Pottery%2C_3000_BC.jpg",
            "year": -3000,
        },
        {
            "title": "Mt. Fuji Tea Bowl",
            "meta": "Edo Japan · Hon'ami Kōetsu · early 17th c.",
            "desc": "A Raku-ware tea bowl with a white glazed rim called Fujisan — Mount Fuji. Kōetsu was a calligrapher, lacquer master, and sword-polisher as well. A bowl meant to be cradled.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Hon%27ami_Koetsu_Fujisan_1.jpg/960px-Hon%27ami_Koetsu_Fujisan_1.jpg",
            "artist": "Hon'ami Kōetsu",
            "year": 1615,
        },
        {
            "title": "Dabotap Pagoda",
            "meta": "Unified Silla · 751 · Bulguksa, Korea",
            "desc": "An ornate twin to the plainer Seokgatap across the courtyard. Two pagodas encoding the Lotus Sutra's doctrine that every Buddha is present in every other.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Dabotap_Pagoda_01.jpg/960px-Dabotap_Pagoda_01.jpg",
            "year": 751,
        },
        {
            "title": "Fushimi Inari-taisha",
            "meta": "Heian period onward · 711 CE · Kyoto",
            "desc": "Ten thousand vermillion torii gates tunnel up a sacred mountain. Each is donated by a business praying for success; the writing on the back is the donor's name.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Torii_path_with_lantern_at_Fushimi_Inari_Taisha_Shrine%2C_Kyoto%2C_Japan.jpg/960px-Torii_path_with_lantern_at_Fushimi_Inari_Taisha_Shrine%2C_Kyoto%2C_Japan.jpg",
            "year": 711,
        },
        {
            "title": "Gyeongbokgung",
            "meta": "Joseon dynasty · 1395 · Seoul",
            "desc": "The principal palace of the Joseon kings. Burned by the Japanese in 1592, rebuilt in 1867, mostly destroyed again under colonial rule — now being re-reconstructed, wing by wing.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/%EA%B4%91%ED%99%94%EB%AC%B8_%EC%9B%94%EB%8C%80.jpg/960px-%EA%B4%91%ED%99%94%EB%AC%B8_%EC%9B%94%EB%8C%80.jpg",
            "year": 1395,
        },
        {
            "title": "Samguk Yusa",
            "meta": "Goryeo · 13th c. · Korea",
            "desc": "\"Memorabilia of the Three Kingdoms\" — a monk's compilation of legends and history. The main surviving source for Korea's founding myths and for early Korean Buddhism.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Memorabilia_of_the_Three_Kingdoms_in_museum.jpg/960px-Memorabilia_of_the_Three_Kingdoms_in_museum.jpg",
            "year": 1280,
        },
        {
            "title": "Tripitaka Koreana",
            "meta": "Goryeo · 1236–1251 · Haeinsa",
            "desc": "81,258 woodblocks of the Buddhist canon carved to petition the gods to repel the Mongols. The blocks still print; stored in a 15th-century hall that manages its own humidity.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Tripitaka_Koreana_02.jpg/960px-Tripitaka_Koreana_02.jpg",
            "year": 1240,
        },
    ],
    "southeast-asia-oceania": [
        {
            "title": "Waka (Māori War Canoe)",
            "meta": "Māori · 18th–19th c. · Aotearoa New Zealand",
            "desc": "Large war canoes carved from a single tōtara trunk. Prows and sternposts carved with ancestors; the hull painted ochre. Rowed by eighty paddlers, two drummers, a chief at the stern.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/c/ce/EarleWarSpeech.jpg",
            "year": 1835,
        },
        {
            "title": "Kris",
            "meta": "Malay Archipelago · 13th c. onward",
            "desc": "An asymmetric wavy dagger with nickel-iron pattern welding. Considered an heirloom with a spirit of its own — some can be named, inherited, or banned from leaving an island.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/4/4d/COLLECTIE_TROPENMUSEUM_Kris_met_schede_TMnr_A-1448.jpg",
            "year": 1700,
        },
        {
            "title": "Thai Silk",
            "meta": "Thai · 13th c. onward",
            "desc": "Hand-reeled mulberry silk dyed and woven into patterned sashes, sarongs, and court textiles. Nearly extinct by 1945; an American expatriate named Jim Thompson revived the industry before vanishing in Malaysia.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Thai_Silk_Cloth_-_Ban_Tha_Sawang.jpg/960px-Thai_Silk_Cloth_-_Ban_Tha_Sawang.jpg",
            "year": 1900,
        },
        {
            "title": "Hmong Textile",
            "meta": "Hmong · traditional · SE Asia",
            "desc": "Reverse-appliqué and cross-stitch panels in jewel colors — \"flower cloth\" (paj ntaub). Often incorporates figures and stories; since the 1970s used to document Hmong migration and war.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Hmong_women_at_Coc_Ly_market%2C_Sapa%2C_Vietnam.jpg/960px-Hmong_women_at_Coc_Ly_market%2C_Sapa%2C_Vietnam.jpg",
            "year": 1900,
        },
        {
            "title": "Batik",
            "meta": "Javanese · traditional · Indonesia",
            "desc": "Patterns drawn in hot wax on cotton, then dyed — the wax resisting the color. Javanese court batiks reserved some motifs for royalty on pain of death.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Batik_Trusmi_Cirebon_%2823%29.jpg/960px-Batik_Trusmi_Cirebon_%2823%29.jpg",
            "year": 1800,
        },
        {
            "title": "Wayang Golek",
            "meta": "Sundanese · 17th c. onward · West Java",
            "desc": "Carved wooden rod puppets, fully dressed in miniature batik. Performed in all-night epics of the Ramayana and Mahabharata — the dalang puppeteer plays every voice.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Wayang_golek_SF_Asian_Art_Museum.JPG/960px-Wayang_golek_SF_Asian_Art_Museum.JPG",
            "year": 1850,
        },
    ],
    "americas": [
        {
            "title": "Bonampak Murals",
            "meta": "Classic Maya · c. 790 CE · Chiapas",
            "desc": "Three rooms painted wall to ceiling: a royal presentation, a battle, a victory dance ending in the torture of captives. The most complete Maya narrative painting to survive.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Zona_arqueologica_Bonampak_01_ID_ZA30_DBannasch.jpg/960px-Zona_arqueologica_Bonampak_01_ID_ZA30_DBannasch.jpg",
            "year": 790,
        },
        {
            "title": "Dresden Codex",
            "meta": "Late Post-Classic Maya · 11th–12th c.",
            "desc": "One of only four surviving Maya codices — 39 sheets of bark paper folded like a screen. Astronomical tables of Venus cycles, eclipses, and the rains. Almost everything else was burned by Spanish friars.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Dresden_Codex_pp.58-62_78.jpg/960px-Dresden_Codex_pp.58-62_78.jpg",
            "year": 1150,
        },
        {
            "title": "Ollantaytambo",
            "meta": "Inca · 15th c. · Sacred Valley",
            "desc": "Fortress and town at the end of the Sacred Valley. Its huge terrace walls are fitted together in the same mortarless style as Machu Picchu — and in 1537 its defenders held off Pizarro's cavalry from them.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Ollantaytambo_-_Heiliges_Tal.jpg/960px-Ollantaytambo_-_Heiliges_Tal.jpg",
            "year": 1450,
        },
        {
            "title": "Paracas Textile",
            "meta": "Paracas · c. 300–200 BCE · Peru",
            "desc": "Embroidered mummy bundles wrapped in layer after layer of cotton and camelid fiber — winged shamans, deities, severed heads — colors still bright after two millennia in the Paracas desert.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Paracas_textile%2C_British_Museum.jpg/960px-Paracas_textile%2C_British_Museum.jpg",
            "year": -250,
        },
        {
            "title": "Codex Mendoza",
            "meta": "Early colonial Mexican · 1541–1542",
            "desc": "Aztec tribute lists and imperial history commissioned for Charles V. Captured by French pirates en route to Spain, ended up in Oxford's Bodleian. The most detailed document we have of Aztec administration.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/CodexMendoza01.jpg/960px-CodexMendoza01.jpg",
            "year": 1542,
        },
        {
            "title": "Calakmul",
            "meta": "Classic Maya · 5th–8th c. · Campeche",
            "desc": "One of the two great Maya superpowers (with Tikal). A kingdom of 50,000 in a rainforest, its two largest pyramids rise 45 meters above the canopy.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Pir%C3%A1mides_de_Calakmul.JPG/960px-Pir%C3%A1mides_de_Calakmul.JPG",
            "year": 700,
        },
        {
            "title": "Hiawatha Belt",
            "meta": "Haudenosaunee · c. 1500 · Northeast Woodlands",
            "desc": "A wampum belt recording the founding of the Iroquois Confederacy: five nations joined by a central tree. Belts were both treaty and record — texts read by running fingers across the beads.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Outdoor_life_and_Indian_stories_-_making_open_air_life_attractive_to_young_Americans_by_telling_them_all_about_woodcraft%2C_signs_and_signaling%2C_the_stars%2C_fishing%2C_camping_-_also_stories_of_noted_%2814566539269%29_%28cropped%29.jpg/960px-thumbnail.jpg",
            "year": 1500,
        },
        {
            "title": "San Agustín Stone Figures",
            "meta": "San Agustín culture · 100 BCE – 800 CE · Colombia",
            "desc": "Over 500 monolithic statues of guardians, jaguar-men, and birth scenes, scattered across an Andean plateau. Who the carvers were, or why they stopped, remains unknown.",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/San_Agustin_%28Huila%29_Village.JPG/960px-San_Agustin_%28Huila%29_Village.JPG",
            "year": 100,
        },
    ],
}


def main() -> None:
    added_total = 0
    for slug, new_works in NEW_WORKS.items():
        path = DATA / f"{slug}.json"
        data = json.loads(path.read_text(encoding="utf-8"))
        existing = {w["title"] for w in data["works"]}
        added = 0
        for w in new_works:
            if w["title"] in existing:
                print(f"  skip (already present): {slug} / {w['title']}")
                continue
            data["works"].append(w)
            added += 1
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"  {slug}: +{added} (now {len(data['works'])})")
        added_total += added
    print(f"\nAdded {added_total} works. Run `python build.py` to regenerate HTML.")


if __name__ == "__main__":
    main()
