#!/usr/bin/env python3
"""Generate world-gallery HTML from data/ JSON.

Reads:
    data/regions.json       — list of regions + museums for the landing page
    data/<slug>.json        — per-region content (title, subtitle, intro, works)

Writes:
    index.html              — landing page
    regions/<slug>.html     — one page per region

Adding a new work: edit data/<slug>.json, add to "works" array, run `python build.py`.
Adding a new region: create data/<slug>.json, add to regions in data/regions.json,
run `python build.py`.
"""
import json
from html import escape
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE / "data"
REGIONS_OUT = HERE / "regions"


def h(s: str) -> str:
    return escape(s, quote=False)


REGION_TPL = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} — World Gallery</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
<!-- Generated by build.py. Edit data/{slug}.json and rerun. -->
<div class="page">
  <header>
    <div>
      <h1>{title}</h1>
      <div class="subtitle">{subtitle}</div>
    </div>
    <a class="back" href="../index.html">← All regions</a>
  </header>
  <p class="intro">
    {intro}
  </p>
  <div class="hint">Click any image to enlarge. Use ← → or close with Esc.</div>
  <div class="grid">
{works}
  </div>
</div>
<script src="lightbox.js"></script>
</body>
</html>
"""

WORK_TPL = """    <article class="work">
      <img src="{image}" alt="{alt}" loading="lazy">
      <div class="body">
        <div class="t">{title}</div>
        <div class="meta">{meta}</div>
        <div class="d">{desc}</div>
      </div>
    </article>
"""

# Index template uses @@TOKEN@@ placeholders because inline CSS contains { }.
INDEX_TPL = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Images — Workspace</title>
<style>
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  :root {
    --bg:#1e2a3a; --fg:#e8ecf1; --muted:#8fa3ba;
    --border:#32445c; --active:#d4a24c; --card:#243347;
  }
  body { font-family: Georgia, serif; background: var(--bg); color: var(--fg); line-height: 1.55; min-height: 100vh; }
  .page { max-width: 1000px; margin: 0 auto; padding: 56px 28px 100px; }
  header { border-bottom: 1px solid var(--border); padding-bottom: 24px; margin-bottom: 36px; display: flex; align-items: baseline; gap: 18px; flex-wrap: wrap; }
  h1 { font-size: 32px; font-weight: 600; letter-spacing: 0.01em; }
  .subtitle { color: var(--muted); font-style: italic; font-size: 16px; flex: 1; min-width: 240px; }
  .back { color: var(--active); text-decoration: none; font-size: 14px; }
  .back:hover { text-decoration: underline; }
  h2.section { font-size: 15px; color: var(--muted); text-transform: uppercase; letter-spacing: 0.12em; font-weight: 600; margin: 28px 0 14px; }
  h2.section:first-of-type { margin-top: 0; }
  .grid { display: grid; gap: 14px; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); }
  .card { display: block; background: var(--card); border: 1px solid var(--border); padding: 18px 20px; text-decoration: none; color: inherit; transition: border-color 0.15s, transform 0.15s; }
  .card:hover { border-color: var(--active); transform: translateY(-1px); }
  .card .t { font-size: 16px; font-weight: 600; color: var(--active); margin-bottom: 4px; }
  .card .d { font-size: 13px; color: var(--muted); line-height: 1.5; }
  .count { color: var(--muted); font-size: 12px; font-style: italic; margin-top: 6px; }
</style>
</head>
<body>
<!-- Generated by build.py. Edit data/regions.json and per-region files, then rerun. -->
<div class="page">
  <header>
    <div>
      <h1>Images</h1>
      <div class="subtitle">A world gallery — art and architecture from everywhere.</div>
    </div>
    <a class="back" href="../../">← Workspace</a>
  </header>

  <h2 class="section">By region <span class="count">@@TOTAL_COUNT@@ works across @@REGION_COUNT@@ regions</span></h2>
  <div class="grid">
@@REGION_CARDS@@
  </div>

  <h2 class="section">Museums</h2>
  <div class="grid">
@@MUSEUM_CARDS@@
  </div>
</div>
</body>
</html>
"""

CARD_TPL = """    <a class="card" href="{href}">
      <div class="t">{title}</div>
      <div class="d">{blurb}</div>
    </a>
"""


def build_region(slug: str, data: dict) -> int:
    works_html = "".join(
        WORK_TPL.format(
            image=w["image"],
            alt=h(w["title"]),
            title=h(w["title"]),
            meta=h(w["meta"]),
            desc=h(w["desc"]),
        )
        for w in data["works"]
    ).rstrip()

    html_out = REGION_TPL.format(
        slug=slug,
        title=h(data["title"]),
        subtitle=h(data["subtitle"]),
        intro=h(data["intro"]),
        works=works_html,
    )
    (REGIONS_OUT / f"{slug}.html").write_text(html_out, encoding="utf-8")
    return len(data["works"])


def build_index(meta: dict, counts: dict[str, int]) -> None:
    region_cards = "".join(
        CARD_TPL.format(
            href=f"regions/{r['slug']}.html",
            title=h(r["title"]),
            blurb=h(r["blurb"]),
        )
        for r in meta["regions"]
    ).rstrip()

    museum_cards = "".join(
        CARD_TPL.format(
            href=m["href"],
            title=h(m["title"]),
            blurb=h(m["blurb"]),
        )
        for m in meta["museums"]
    ).rstrip()

    total = sum(counts.values())
    html_out = (
        INDEX_TPL
        .replace("@@REGION_CARDS@@", region_cards)
        .replace("@@MUSEUM_CARDS@@", museum_cards)
        .replace("@@TOTAL_COUNT@@", str(total))
        .replace("@@REGION_COUNT@@", str(len(meta["regions"])))
    )
    (HERE / "index.html").write_text(html_out, encoding="utf-8")


def main() -> None:
    meta = json.loads((DATA / "regions.json").read_text(encoding="utf-8"))
    counts: dict[str, int] = {}
    for r in meta["regions"]:
        slug = r["slug"]
        data = json.loads((DATA / f"{slug}.json").read_text(encoding="utf-8"))
        counts[slug] = build_region(slug, data)
        print(f"  {slug}: {counts[slug]} works")
    build_index(meta, counts)
    print(f"\nBuilt {len(meta['regions'])} regions + index. {sum(counts.values())} works total.")


if __name__ == "__main__":
    main()
