#!/usr/bin/env python3
"""Generate world-gallery HTML from data/ JSON.

Reads:
    data/regions.json       — list of regions + museums for the landing page
    data/<slug>.json        — per-region content (title, subtitle, intro, works)

Writes:
    index.html              — landing page
    regions/<slug>.html     — one page per region
    artists.html            — works grouped by named artist (optional `artist`
                              field on any work opts it into this view)

Adding a new work: edit data/<slug>.json, add to "works" array, run `python build.py`.
Adding a new region: create data/<slug>.json, add to regions in data/regions.json,
run `python build.py`.
"""
import json
import re
from html import escape
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE / "data"
REGIONS_OUT = HERE / "regions"


def h(s: str) -> str:
    return escape(s, quote=False)


def slugify(s: str) -> str:
    s = re.sub(r"[^\w\s-]", "", s, flags=re.UNICODE).strip().lower()
    return re.sub(r"[\s_-]+", "-", s)


_SURNAME_OVERRIDES = {
    # Names where last-word-as-surname gets the wrong answer.
    "Pieter Bruegel the Elder": "bruegel",
    "Leonardo da Vinci": "leonardo",  # "da Vinci" means "of Vinci"; indexed under L
    # Chinese names — family name first in the original ordering.
    "Gu Kaizhi": "gu",
    "Guo Xi": "guo",
    "Zhang Zeduan": "zhang",
}


def artist_sort_key(name: str) -> tuple[str, str]:
    """Sort by surname heuristic (or override), then by full name."""
    if name in _SURNAME_OVERRIDES:
        return (_SURNAME_OVERRIDES[name], name.lower())
    parts = name.replace(".", "").split()
    surname = parts[-1] if parts else name
    return (surname.lower(), name.lower())


REGION_TPL = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} — World Gallery</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
<!-- Generated by build.py. Edit data/{slug}.json and rerun. -->
<div class="page">
  <header>
    <div>
      <h1>{title}</h1>
      <div class="subtitle">{subtitle}</div>
    </div>
    <a class="back" href="../index.html">← All regions</a>
  </header>
  <p class="intro">
    {intro}
  </p>
  <div class="hint">Click any image to enlarge. Use ← → or close with Esc.</div>
  <div class="grid">
{works}
  </div>
</div>
<script src="lightbox.js"></script>
</body>
</html>
"""

WORK_TPL = """    <article class="work">
      <img src="{image}" alt="{alt}" loading="lazy">
      <div class="body">
        <div class="t">{title}</div>
        <div class="meta">{meta}</div>
        <div class="d">{desc}</div>
      </div>
    </article>
"""

# Index template uses @@TOKEN@@ placeholders because inline CSS contains { }.
INDEX_TPL = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Images — Workspace</title>
<style>
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  :root {
    --bg:#1e2a3a; --fg:#e8ecf1; --muted:#8fa3ba;
    --border:#32445c; --active:#d4a24c; --card:#243347;
  }
  body { font-family: Georgia, serif; background: var(--bg); color: var(--fg); line-height: 1.55; min-height: 100vh; }
  .page { max-width: 1000px; margin: 0 auto; padding: 56px 28px 100px; }
  header { border-bottom: 1px solid var(--border); padding-bottom: 24px; margin-bottom: 36px; display: flex; align-items: baseline; gap: 18px; flex-wrap: wrap; }
  h1 { font-size: 32px; font-weight: 600; letter-spacing: 0.01em; }
  .subtitle { color: var(--muted); font-style: italic; font-size: 16px; flex: 1; min-width: 240px; }
  .back { color: var(--active); text-decoration: none; font-size: 14px; }
  .back:hover { text-decoration: underline; }
  h2.section { font-size: 15px; color: var(--muted); text-transform: uppercase; letter-spacing: 0.12em; font-weight: 600; margin: 28px 0 14px; }
  h2.section:first-of-type { margin-top: 0; }
  .grid { display: grid; gap: 14px; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); }
  .card { display: block; background: var(--card); border: 1px solid var(--border); padding: 18px 20px; text-decoration: none; color: inherit; transition: border-color 0.15s, transform 0.15s; }
  .card:hover { border-color: var(--active); transform: translateY(-1px); }
  .card .t { font-size: 16px; font-weight: 600; color: var(--active); margin-bottom: 4px; }
  .card .d { font-size: 13px; color: var(--muted); line-height: 1.5; }
  .count { color: var(--muted); font-size: 12px; font-style: italic; margin-top: 6px; }
</style>
</head>
<body>
<!-- Generated by build.py. Edit data/regions.json and per-region files, then rerun. -->
<div class="page">
  <header>
    <div>
      <h1>Images</h1>
      <div class="subtitle">A world gallery — art and architecture from everywhere.</div>
    </div>
    <a class="back" href="../../">← Workspace</a>
  </header>

  <h2 class="section">By region <span class="count">@@TOTAL_COUNT@@ works across @@REGION_COUNT@@ regions</span></h2>
  <div class="grid">
@@REGION_CARDS@@
  </div>

  <h2 class="section">By artist <span class="count">@@ARTIST_COUNT@@ named artists, @@ARTIST_WORK_COUNT@@ works</span></h2>
  <div class="grid">
@@ARTIST_CARDS@@
  </div>

  <h2 class="section">Museums</h2>
  <div class="grid">
@@MUSEUM_CARDS@@
  </div>
</div>
</body>
</html>
"""

CARD_TPL = """    <a class="card" href="{href}">
      <div class="t">{title}</div>
      <div class="d">{blurb}</div>
    </a>
"""

ARTISTS_TPL = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>By Artist — World Gallery</title>
<link rel="stylesheet" href="regions/style.css">
</head>
<body>
<!-- Generated by build.py. -->
<div class="page">
  <header>
    <div>
      <h1>By Artist</h1>
      <div class="subtitle">Named makers, grouped. Most ancient and vernacular works are anonymous or collective — those live in the regional views.</div>
    </div>
    <a class="back" href="index.html">← All regions</a>
  </header>
  <div class="hint">Click any image to enlarge. Use ← → or close with Esc.</div>
  <nav class="artist-toc">
@@TOC@@
  </nav>
@@SECTIONS@@
</div>
<script src="regions/lightbox.js"></script>
</body>
</html>
"""

ARTIST_SECTION_TPL = """  <section class="artist-section" id="{slug}">
    <h2 class="artist-name">{name}<span class="artist-count">{count} {noun}</span></h2>
    <div class="grid">
{works}
    </div>
  </section>
"""

ARTIST_TOC_TPL = """    <a href="#{slug}">{name}<span class="c">{count}</span></a>
"""


def build_region(slug: str, data: dict) -> int:
    works_html = "".join(
        WORK_TPL.format(
            image=w["image"],
            alt=h(w["title"]),
            title=h(w["title"]),
            meta=h(w["meta"]),
            desc=h(w["desc"]),
        )
        for w in data["works"]
    ).rstrip()

    html_out = REGION_TPL.format(
        slug=slug,
        title=h(data["title"]),
        subtitle=h(data["subtitle"]),
        intro=h(data["intro"]),
        works=works_html,
    )
    (REGIONS_OUT / f"{slug}.html").write_text(html_out, encoding="utf-8")
    return len(data["works"])


def collect_artists(meta: dict) -> dict[str, list[dict]]:
    artists: dict[str, list[dict]] = {}
    for r in meta["regions"]:
        data = json.loads((DATA / f"{r['slug']}.json").read_text(encoding="utf-8"))
        for w in data["works"]:
            name = w.get("artist")
            if name:
                artists.setdefault(name, []).append(w)
    return artists


def build_artists(artists: dict[str, list[dict]]) -> tuple[int, int]:
    if not artists:
        # Still write a stub so the link from index doesn't 404.
        (HERE / "artists.html").write_text(
            ARTISTS_TPL.replace("@@TOC@@", "").replace("@@SECTIONS@@", "<p class=\"intro\">No artist-tagged works yet.</p>"),
            encoding="utf-8",
        )
        return 0, 0

    names = sorted(artists.keys(), key=artist_sort_key)
    toc = "".join(
        ARTIST_TOC_TPL.format(slug=slugify(n), name=h(n), count=len(artists[n]))
        for n in names
    ).rstrip()

    sections = ""
    total_works = 0
    for name in names:
        works = artists[name]
        works_html = "".join(
            WORK_TPL.format(
                image=w["image"],
                alt=h(w["title"]),
                title=h(w["title"]),
                meta=h(w["meta"]),
                desc=h(w["desc"]),
            )
            for w in works
        ).rstrip()
        sections += ARTIST_SECTION_TPL.format(
            slug=slugify(name),
            name=h(name),
            count=len(works),
            noun="work" if len(works) == 1 else "works",
            works=works_html,
        )
        total_works += len(works)

    html_out = (
        ARTISTS_TPL
        .replace("@@TOC@@", toc)
        .replace("@@SECTIONS@@", sections.rstrip())
    )
    (HERE / "artists.html").write_text(html_out, encoding="utf-8")
    return len(names), total_works


def build_index(meta: dict, counts: dict[str, int], artists: dict[str, list[dict]]) -> None:
    region_cards = "".join(
        CARD_TPL.format(
            href=f"regions/{r['slug']}.html",
            title=h(r["title"]),
            blurb=h(r["blurb"]),
        )
        for r in meta["regions"]
    ).rstrip()

    # One card per artist, sorted by surname heuristic.
    names = sorted(artists.keys(), key=artist_sort_key)
    artist_cards = "".join(
        CARD_TPL.format(
            href=f"artists.html#{slugify(n)}",
            title=h(n),
            blurb=f"{len(artists[n])} {'work' if len(artists[n]) == 1 else 'works'}",
        )
        for n in names
    ).rstrip()

    museum_cards = "".join(
        CARD_TPL.format(
            href=m["href"],
            title=h(m["title"]),
            blurb=h(m["blurb"]),
        )
        for m in meta["museums"]
    ).rstrip()

    total = sum(counts.values())
    artist_work_count = sum(len(v) for v in artists.values())
    html_out = (
        INDEX_TPL
        .replace("@@REGION_CARDS@@", region_cards)
        .replace("@@ARTIST_CARDS@@", artist_cards)
        .replace("@@MUSEUM_CARDS@@", museum_cards)
        .replace("@@TOTAL_COUNT@@", str(total))
        .replace("@@REGION_COUNT@@", str(len(meta["regions"])))
        .replace("@@ARTIST_COUNT@@", str(len(artists)))
        .replace("@@ARTIST_WORK_COUNT@@", str(artist_work_count))
    )
    (HERE / "index.html").write_text(html_out, encoding="utf-8")


def main() -> None:
    meta = json.loads((DATA / "regions.json").read_text(encoding="utf-8"))
    counts: dict[str, int] = {}
    for r in meta["regions"]:
        slug = r["slug"]
        data = json.loads((DATA / f"{slug}.json").read_text(encoding="utf-8"))
        counts[slug] = build_region(slug, data)
        print(f"  {slug}: {counts[slug]} works")
    artists = collect_artists(meta)
    n_artists, n_artist_works = build_artists(artists)
    build_index(meta, counts, artists)
    print(
        f"\nBuilt {len(meta['regions'])} regions + index + artist view. "
        f"{sum(counts.values())} works total ({n_artist_works} by {n_artists} named artists)."
    )


if __name__ == "__main__":
    main()
