#!/usr/bin/env python3
"""Generate world-gallery HTML from data/ JSON.

Reads:
    data/regions.json       — list of regions (+ continent) and museums
    data/<slug>.json        — per-region content (title, subtitle, intro, works)

Writes:
    index.html              — landing page (regions grouped by continent,
                              artists with 2+ works, museums)
    regions/<slug>.html     — one page per region (with prev/next footer)
    artists.html            — works grouped by named artist
    all.html                — every work on one page, live search filter

Shared: style.css and lightbox.js at the top level.

Adding a new work: edit data/<slug>.json, rerun `python build.py`.
Adding a new region: create data/<slug>.json, add entry in data/regions.json,
rerun.
"""
import json
import re
from html import escape
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE / "data"
REGIONS_OUT = HERE / "regions"


def h(s: str) -> str:
    return escape(s, quote=False)


def h_attr(s: str) -> str:
    return escape(s, quote=True)


def slugify(s: str) -> str:
    s = re.sub(r"[^\w\s-]", "", s, flags=re.UNICODE).strip().lower()
    return re.sub(r"[\s_-]+", "-", s)


_SURNAME_OVERRIDES = {
    "Pieter Bruegel the Elder": "bruegel",
    "Leonardo da Vinci": "leonardo",
    "Gu Kaizhi": "gu",
    "Guo Xi": "guo",
    "Zhang Zeduan": "zhang",
}


def artist_sort_key(name: str) -> tuple[str, str]:
    if name in _SURNAME_OVERRIDES:
        return (_SURNAME_OVERRIDES[name], name.lower())
    parts = name.replace(".", "").split()
    surname = parts[-1] if parts else name
    return (surname.lower(), name.lower())


# ---------------------------------------------------------------------------
# Shared nav
# ---------------------------------------------------------------------------

NAV_TPL = """<nav class="top-nav">
  <a href="{workspace}" class="nav-ws" title="Back to Workspace">&larr;</a>
  <a href="{home}" class="nav-brand">World Gallery</a>
  <div class="nav-links">
    <a href="{home}"{cls_regions}>Regions</a>
    <a href="{artists}"{cls_artists}>Artists</a>
    <a href="{all_}"{cls_all}>All works</a>
  </div>
</nav>
"""


def make_nav(current: str, in_regions_dir: bool = False) -> str:
    prefix = "../" if in_regions_dir else ""
    return NAV_TPL.format(
        workspace=f"{prefix}../",
        home=f"{prefix}index.html",
        artists=f"{prefix}artists.html",
        all_=f"{prefix}all.html",
        cls_regions=' class="active"' if current == "regions" else "",
        cls_artists=' class="active"' if current == "artists" else "",
        cls_all=' class="active"' if current == "all" else "",
    )


# ---------------------------------------------------------------------------
# Work card
# ---------------------------------------------------------------------------

WORK_TPL = """    <article class="work">
      <img src="{image}" alt="{alt}" loading="lazy">
      <div class="body">
        <div class="t">{title}</div>
        <div class="meta">{meta}</div>
        <div class="d">{desc}</div>
      </div>
    </article>
"""

ALL_WORK_TPL = """    <article class="work" data-search="{search}">
      <img src="{image}" alt="{alt}" loading="lazy">
      <div class="body">
        <div class="region-badge">{region}</div>
        <div class="t">{title}</div>
        <div class="meta">{meta}</div>
        <div class="d">{desc}</div>
      </div>
    </article>
"""


def render_work(w: dict) -> str:
    return WORK_TPL.format(
        image=w["image"],
        alt=h(w["title"]),
        title=h(w["title"]),
        meta=h(w["meta"]),
        desc=h(w["desc"]),
    )


def render_all_work(w: dict, region_title: str) -> str:
    tokens = [w["title"], w["meta"], w.get("desc", ""), w.get("artist", ""), region_title]
    search = " ".join(tokens).lower()
    return ALL_WORK_TPL.format(
        image=w["image"],
        alt=h(w["title"]),
        title=h(w["title"]),
        meta=h(w["meta"]),
        desc=h(w["desc"]),
        region=h(region_title),
        search=h_attr(search),
    )


# ---------------------------------------------------------------------------
# Region page
# ---------------------------------------------------------------------------

REGION_TPL = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} &mdash; World Gallery</title>
<link rel="stylesheet" href="../style.css">
</head>
<body>
<!-- Generated by build.py. Edit data/{slug}.json and rerun. -->
{nav}
<div class="page">
  <header class="page-header">
    <div>
      <h1>{title}</h1>
      <div class="subtitle">{subtitle}</div>
    </div>
  </header>
  <p class="intro">
    {intro}
  </p>
  <div class="hint">Click any image to enlarge. Use &larr; &rarr; or close with Esc.</div>
  <div class="grid">
{works}
  </div>
  <footer class="region-footer">
    <a href="{prev_href}"><span class="arrow">&larr;</span>{prev_title}</a>
    <a href="{next_href}">{next_title}<span class="arrow">&rarr;</span></a>
  </footer>
</div>
<script src="../lightbox.js"></script>
</body>
</html>
"""


def build_region(slug: str, data: dict, neighbors: tuple[dict, dict]) -> int:
    works_html = "".join(render_work(w) for w in data["works"]).rstrip()
    prev, next_ = neighbors
    html_out = REGION_TPL.format(
        slug=slug,
        title=h(data["title"]),
        subtitle=h(data["subtitle"]),
        intro=h(data["intro"]),
        works=works_html,
        nav=make_nav("regions", in_regions_dir=True),
        prev_href=f"{prev['slug']}.html",
        prev_title=h(prev["title"]),
        next_href=f"{next_['slug']}.html",
        next_title=h(next_["title"]),
    )
    (REGIONS_OUT / f"{slug}.html").write_text(html_out, encoding="utf-8")
    return len(data["works"])


# ---------------------------------------------------------------------------
# Artists page
# ---------------------------------------------------------------------------

ARTISTS_TPL = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>By Artist &mdash; World Gallery</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
<!-- Generated by build.py. -->
@@NAV@@
<div class="page">
  <header class="page-header">
    <div>
      <h1>By Artist</h1>
      <div class="subtitle">Named makers, grouped. Anonymous and collective works live in the regional views.</div>
    </div>
  </header>
  <div class="hint">Click any image to enlarge. Use &larr; &rarr; or close with Esc.</div>
  <nav class="artist-toc">
@@TOC@@
  </nav>
@@SECTIONS@@
</div>
<script src="lightbox.js"></script>
</body>
</html>
"""

ARTIST_SECTION_TPL = """  <section class="artist-section" id="{slug}">
    <h2 class="artist-name">{name}<span class="artist-count">{count} {noun}</span></h2>
    <div class="grid">
{works}
    </div>
  </section>
"""

ARTIST_TOC_TPL = """    <a href="#{slug}">{name}<span class="c">{count}</span></a>
"""


def collect_artists(meta: dict) -> dict[str, list[dict]]:
    artists: dict[str, list[dict]] = {}
    for r in meta["regions"]:
        data = json.loads((DATA / f"{r['slug']}.json").read_text(encoding="utf-8"))
        for w in data["works"]:
            name = w.get("artist")
            if name:
                artists.setdefault(name, []).append(w)
    return artists


def build_artists(artists: dict[str, list[dict]]) -> tuple[int, int]:
    nav = make_nav("artists")
    if not artists:
        html_out = (
            ARTISTS_TPL
            .replace("@@NAV@@", nav)
            .replace("@@TOC@@", "")
            .replace("@@SECTIONS@@", '<p class="intro">No artist-tagged works yet.</p>')
        )
        (HERE / "artists.html").write_text(html_out, encoding="utf-8")
        return 0, 0

    names = sorted(artists.keys(), key=artist_sort_key)
    toc = "".join(
        ARTIST_TOC_TPL.format(slug=slugify(n), name=h(n), count=len(artists[n]))
        for n in names
    ).rstrip()

    sections = ""
    total_works = 0
    for name in names:
        works = artists[name]
        works_html = "".join(render_work(w) for w in works).rstrip()
        sections += ARTIST_SECTION_TPL.format(
            slug=slugify(name),
            name=h(name),
            count=len(works),
            noun="work" if len(works) == 1 else "works",
            works=works_html,
        )
        total_works += len(works)

    html_out = (
        ARTISTS_TPL
        .replace("@@NAV@@", nav)
        .replace("@@TOC@@", toc)
        .replace("@@SECTIONS@@", sections.rstrip())
    )
    (HERE / "artists.html").write_text(html_out, encoding="utf-8")
    return len(names), total_works


# ---------------------------------------------------------------------------
# All works page (with live search)
# ---------------------------------------------------------------------------

ALL_TPL = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>All Works &mdash; World Gallery</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
<!-- Generated by build.py. -->
@@NAV@@
<div class="page">
  <header class="page-header">
    <div>
      <h1>All Works</h1>
      <div class="subtitle">Every piece, searchable. Type a title, culture, artist, period, or region.</div>
    </div>
  </header>
  <div class="all-search">
    <input type="text" id="search-input" placeholder="Search @@TOTAL@@ works&hellip; (e.g. Monet, Buddhist, bronze)" autofocus>
    <div class="result-count" id="result-count">@@TOTAL@@ works</div>
  </div>
  <div class="grid" id="all-grid">
@@WORKS@@
  </div>
  <div class="no-results" id="no-results">No works match that search.</div>
</div>
<script src="lightbox.js"></script>
<script>
(function() {
  const input = document.getElementById('search-input');
  const works = Array.from(document.querySelectorAll('#all-grid .work'));
  const count = document.getElementById('result-count');
  const empty = document.getElementById('no-results');
  const total = works.length;

  function filter() {
    const q = input.value.trim().toLowerCase();
    let visible = 0;
    for (const w of works) {
      const match = !q || w.dataset.search.includes(q);
      w.style.display = match ? '' : 'none';
      if (match) visible++;
    }
    count.textContent = q ? (visible + ' of ' + total + ' works') : (total + ' works');
    empty.style.display = (visible === 0) ? 'block' : 'none';
  }

  input.addEventListener('input', filter);
})();
</script>
</body>
</html>
"""


def build_all_works(meta: dict) -> int:
    works_html_chunks = []
    total = 0
    for r in meta["regions"]:
        data = json.loads((DATA / f"{r['slug']}.json").read_text(encoding="utf-8"))
        for w in data["works"]:
            works_html_chunks.append(render_all_work(w, r["title"]))
            total += 1
    works_html = "".join(works_html_chunks).rstrip()
    nav = make_nav("all")
    html_out = (
        ALL_TPL
        .replace("@@NAV@@", nav)
        .replace("@@WORKS@@", works_html)
        .replace("@@TOTAL@@", str(total))
    )
    (HERE / "all.html").write_text(html_out, encoding="utf-8")
    return total


# ---------------------------------------------------------------------------
# Landing page
# ---------------------------------------------------------------------------

INDEX_TPL = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>World Gallery</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
<!-- Generated by build.py. Edit data/regions.json and per-region files, then rerun. -->
@@NAV@@
<div class="page">
  <header class="page-header">
    <div>
      <h1>World Gallery</h1>
      <div class="subtitle">Art and architecture from everywhere &mdash; @@TOTAL_COUNT@@ works, @@REGION_COUNT@@ regions, @@ARTIST_COUNT@@ named artists.</div>
    </div>
  </header>

  <h2 class="section">By region</h2>
@@REGION_GROUPS@@

  <h2 class="section">By artist <span class="count">featured makers &mdash; see all @@ARTIST_COUNT@@ &rarr;</span></h2>
  <div class="card-grid">
@@ARTIST_CARDS@@
  </div>

  <h2 class="section">Museums</h2>
  <div class="card-grid">
@@MUSEUM_CARDS@@
  </div>
</div>
</body>
</html>
"""

CARD_TPL = """    <a class="card" href="{href}">
      <div class="t">{title}</div>
      <div class="d">{blurb}</div>
    </a>
"""

CARD_MORE_TPL = """    <a class="card card-more" href="{href}">
      <div>
        <div class="t">{title}</div>
        <div class="d">{blurb}</div>
      </div>
    </a>
"""


def build_index(meta: dict, counts: dict[str, int], artists: dict[str, list[dict]]) -> None:
    # Regions grouped by continent, preserving regions.json order within each group.
    groups: dict[str, list[dict]] = {}
    group_order: list[str] = []
    for r in meta["regions"]:
        c = r.get("continent", "Other")
        if c not in groups:
            groups[c] = []
            group_order.append(c)
        groups[c].append(r)

    region_groups_html = ""
    for continent in group_order:
        cards = "".join(
            CARD_TPL.format(
                href=f"regions/{r['slug']}.html",
                title=h(r["title"]),
                blurb=h(r["blurb"]),
            )
            for r in groups[continent]
        ).rstrip()
        region_groups_html += (
            f'  <h3 class="continent">{h(continent)}</h3>\n'
            f'  <div class="card-grid">\n{cards}\n  </div>\n'
        )

    # Featured artists: those with >= 2 works, sorted by count desc then surname.
    featured = sorted(
        ((name, works) for name, works in artists.items() if len(works) >= 2),
        key=lambda pair: (-len(pair[1]), artist_sort_key(pair[0])),
    )
    artist_cards = "".join(
        CARD_TPL.format(
            href=f"artists.html#{slugify(name)}",
            title=h(name),
            blurb=f"{len(works)} works",
        )
        for name, works in featured
    )
    artist_cards += CARD_MORE_TPL.format(
        href="artists.html",
        title=h("View all artists"),
        blurb=f"{len(artists)} named makers",
    )
    artist_cards = artist_cards.rstrip()

    museum_cards = "".join(
        CARD_TPL.format(
            href=m["href"],
            title=h(m["title"]),
            blurb=h(m["blurb"]),
        )
        for m in meta["museums"]
    ).rstrip()

    total = sum(counts.values())
    html_out = (
        INDEX_TPL
        .replace("@@NAV@@", make_nav("regions"))
        .replace("@@REGION_GROUPS@@", region_groups_html.rstrip())
        .replace("@@ARTIST_CARDS@@", artist_cards)
        .replace("@@MUSEUM_CARDS@@", museum_cards)
        .replace("@@TOTAL_COUNT@@", str(total))
        .replace("@@REGION_COUNT@@", str(len(meta["regions"])))
        .replace("@@ARTIST_COUNT@@", str(len(artists)))
    )
    (HERE / "index.html").write_text(html_out, encoding="utf-8")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    meta = json.loads((DATA / "regions.json").read_text(encoding="utf-8"))
    regions = meta["regions"]
    counts: dict[str, int] = {}
    for i, r in enumerate(regions):
        slug = r["slug"]
        data = json.loads((DATA / f"{slug}.json").read_text(encoding="utf-8"))
        prev = regions[(i - 1) % len(regions)]
        next_ = regions[(i + 1) % len(regions)]
        counts[slug] = build_region(slug, data, (prev, next_))
        print(f"  {slug}: {counts[slug]} works")
    artists = collect_artists(meta)
    n_artists, n_artist_works = build_artists(artists)
    total_all = build_all_works(meta)
    build_index(meta, counts, artists)
    print(
        f"\nBuilt {len(regions)} regions + index + artists + all-works. "
        f"{total_all} works total ({n_artist_works} by {n_artists} named artists)."
    )


if __name__ == "__main__":
    main()
